//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraficoClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCita
    {
        public int IdCita { get; set; }
        public string CodPaciente { get; set; }
        public string CodMedico { get; set; }
        public System.DateTime FechaCita { get; set; }
        public string Motivo { get; set; }
    
        public virtual TMedico TMedico { get; set; }
        public virtual TPaciente TPaciente { get; set; }
    }
}
